// LOGIN
export const SAVE_USER_PROFILE = "SAVE_USER_PROFILE";
export const SIGNOUT = "SIGNOUT";

export const GET_CURRENT_USER = "GET_CURRENT_USER";

export const SAVE_USER_STATE_TO_LOCAL_STORAGE =
  "SAVE_USER_STATE_TO_LOCAL_STORAGE";
